config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      get 'raj'
    end
    member do
      get 'image'
    end
  end
  get 'auth/:provider/callback', to: 'users#facebook'
  resources 'users' do
    collection do
      get "sign_in"
      post "authentication"
      delete "logout"
      get 'download_in_csv'
    end
  end
  get 'sign_in', to: "users#sign_in"
  get 'registration', to: "users#new"
  namespace :api do
    resources :users, only: [:index, :create, :update, :destroy]
  end
  # match 'hello', to: "users#hello" , via: [:get, :post]

  root to: "users#index"

get "purchase_item", to: "products#make_payment"
post "process_payment" , to: "products#process_payment"
get 'profile', action: :show, controller: 'users'
get 'profile', to:  'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password, presence: true, length: { maximum: 8, minimum: 4 } #,confirmation: true, length: { maximum: 8, minimum: 4 }
  validates :confirm_password, presence: true
  has_one :image , as: :entity
  accepts_nested_attributes_for  :image
  has_many :articles
  # attr_accessor :image
  #class method
  def self.authenticate(email, password)
    return where(email: email, password: Digest::MD5.hexdigest(password)).first
  end

  before_create :encrypt_password
  def encrypt_password
    if not password.nil?
      self.password = Digest::MD5.hexdigest(password)
      self.confirm_password = Digest::MD5.hexdigest(confirm_password)
    end
  end
  after_destroy :save_into_file
  def save_into_file
    File.open("#{Rails.root}/public/#{self.id}.json", "w") { |foo| foo.write(self.to_json)}
  end

  after_validation :verify_passwords
  def verify_passwords
    if password != confirm_password
        errors.add(:base, "password and confirm password are not equal")
    end
  end
  # class PasswordValidator < ActiveModel::EachValidator
  #   def validate_each(record, attribute, value)
  #       record.errors.add attribute, (options[:message] || "password and confirm password are not equal") unless
  #         password == confirm_password
  #       end
  # end
  def self.omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.token = auth.credentials.token
      user.email = auth.info.email
      user.expires_at = Time.at(auth.credentials.expires_at)
      user.profile_image = auth.info.image
      user.save(validate: false)
      return user
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :verify_session

  def index
    @users = User.all
    respond_to do | format |
      format.json {render json: {body: @users, code: 200}}
    end
  end
  def create
    @user = User.new(user_params)
    respond_to do | format |
      if @user.save
        format.json {render json: {body: @user, code: 204, message: "Successfully added users"}}
      else
        format.json {render json: {body: @user.errors, code: 304, message: "OOPS! Try again!"}}
      end
    end
  end
  def update
    @user = User.find(params[:id])
    respond_to do | format |
      if @user.update_columns(user_params.to_h)
        format.json {render json: {body: @user, code: 204, message: "Successfully updated users"}}
      else
        format.json {render json: {body: @user.errors, code: 304, message: "OOPS! Try again!"}}
      end
    end
  end
  def destroy
      @user = User.find(params[:id])
      @user.delete
      respond_to do | format |
        format.json {render json: {message: "Deleted Successfully"}}
      end
  end
  protected
  def user_params
    params.require(:user).permit!
  end
end

app/controllers/users_controller.rb
require 'csv'
class UsersController < ApplicationController

  skip_before_action :verify_session, only: [:sign_in, :authentication, :new, :create, :facebook]

  def index
    @users = User.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @user.build_image # has_one
  end
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailMailer.welcome(@user).deliver_now!
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :new
    end
  end
  def facebook
    user = User.omniauth(request.env['omniauth.auth'])
    if user
      session[:user_id] = user.id
      redirect_to users_path
    else
      redirect_to root_url
    end
  end
  def download_in_csv
    CSV.open("#{Rails.root}/public/users.csv", "w") do | csv |
      csv << User.column_names
      User.all.each do | user |
        csv << ActiveRecord::Base.connection.select_one("select * from users where id = #{user.id}").values
      end
    end
    send_file "#{Rails.root}/public/users.csv", :disposition=> "attachment"
  end
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_path
    end
  end
  def logout
    session[:user_id] = nil
    redirect_to users_path
  end
  def authentication
    @user = User.authenticate(params[:email], params[:password])
    unless @user.nil?
      session[:user_id] = @user.id
      redirect_to users_path
    else
      redirect_to sign_in_users_path
    end
  end
  protected
  def user_params
    params.require(:user).permit!
  end
end

# {user: {name: 'name', :email: 'email'}}  form_for
# {{name: 'name', :email: 'email'}}  form_tag

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def return_user_id
    session[:user_id]
  end
  def profile_pic
    user = User.find return_user_id
    if not user.profile_image.nil?
      user.profile_image
    end
  end
end

app/views/users/edit.html.erb
<%= form_for @user do | f| %>
  <table>
    <tr>
        <td><%= f.label :name%></td>
        <td><%= f.text_field :name%></td>
      </tr>
        <tr>
          <td><%= f.label :email%></td>
          <td><%= f.email_field :email%></td>
      </tr>
    <tr>
      <td><%= f.label :mobile_no%></td>
      <td><%= f.text_field :mobile_no%></td>
    </tr>
    <tr>
      <td><%= f.label :address%></td>
      <td><%= f.text_field :address%></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit "Sign Up"%></td>
    </tr>
  </table>
<%end%>

<%= link_to "Home", users_path%>

app/views/users/index.html.erb
<%= hello(return_user_id) %>
<%= image_tag profile_pic if profile_pic.present?%>
<table class="table table-striped">
  <tr>
    <th>Profile Pic</th>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile no</th>
    <th>Address</th>
    <th><%= link_to "Download into CSV", download_in_csv_users_path%></th>
    </tr>
    <% @users.each do | user | %>
      <tr>
        <td><%= image_tag user.image.photo(:thumb) unless user.image.nil?%></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.mobile_no %></td>
        <td><%= user.address %></td>
        <td><%= link_to "Show", user_path(user) %></td>
        <td><%= link_to "Edit", edit_user_path(user) %></td>
        <td><%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"}  %></td>
        </tr>
    <%end%>
  </table>
<%= will_paginate @users %>
<%= link_to "Add users", new_user_path%>

app/views/users/new.html.erb
<% if @user.errors.full_messages.any? %>
<ul>
  <% @user.errors.full_messages.each do |error_message| %>
    <li><%= error_message %> </li>
  <% end %>
  </ul>
<% end %>

<%= form_for @user do | f| %>
  <table class="table table-striped">
    <tr>
        <td><%= f.label :name%></td>
        <td><%= f.text_field :name%></td>
      </tr>
        <tr>
          <td><%= f.label :email%></td>
          <td><%= f.email_field :email%></td>
      </tr>
      <tr>
        <td><%= f.label :password%></td>
        <td><%= f.password_field :password%></td>
    </tr>
    <tr>
      <td><%= f.label :confirm_password%></td>
      <td><%= f.password_field :confirm_password%></td>
    </tr>
    <tr>
      <td><%= f.label :mobile_no%></td>
      <td><%= f.text_field :mobile_no%></td>
    </tr>
    <tr>
      <td><%= f.label :address%></td>
      <td><%= f.text_field :address%></td>
    </tr>
    <tr>
      <%= f.fields_for :image  do | im |%>
        <td><%= im.label :photo%></td>
        <td><%= im.file_field :photo%></td>
      <%end%>
    </tr>
      <td><%= link_to "Sign In" , sign_in_users_path%></td>
      <td><%= f.submit "Sign Up"%></td>
    </tr>
  </table>
<%end%>

<!-- %= link_to "Home", users_path% -->

app/views/users/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile no</th>
    <th>Address</th>
    </tr>
      <tr>
        <td><%= @user.name %></td>
        <td><%= @user.email %></td>
        <td><%= @user.mobile_no %></td>
        <td><%= @user.address %></td>
        <td><%= link_to "Edit", edit_user_path(@user) %></td>
        <td><%= link_to "Delete", @user, method: :delete, data: {confirm: "Are you sure?"}  %></td>
        </tr>
  </table>
<%= link_to "Add users", new_user_path%>

app/views/users/sign_in.html.erb
<%= form_tag action: :authentication , method: :post do  %>
  <table class="table table-striped">
    <tr>
      <td><%= label_tag :email%></td>
      <td><%= email_field_tag :email%></td>
      </tr>
      <tr>
        <td><%= label_tag :password%></td>
        <td><%= password_field_tag :password%></td>
        </tr>
        <tr>
          <td><%= link_to "Sign Up", registration_path%></td>
          <td><%= submit_tag "Sign In"%></td>
          </tr>
    </table>
<%end%>

<%= link_to "Facebook", "/auth/facebook" %>