config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      get 'raj'
    end
    member do
      get 'image'
    end
  end
  get 'auth/:provider/callback', to: 'users#facebook'
  resources 'users' do
    collection do
      get "sign_in"
      post "authentication"
      delete "logout"
      get 'download_in_csv'
    end
  end
  get 'sign_in', to: "users#sign_in"
  get 'registration', to: "users#new"
  namespace :api do
    resources :users, only: [:index, :create, :update, :destroy]
  end
  # match 'hello', to: "users#hello" , via: [:get, :post]

  root to: "users#index"

get "purchase_item", to: "products#make_payment"
post "process_payment" , to: "products#process_payment"
get 'profile', action: :show, controller: 'users'
get 'profile', to:  'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images, as: :entity
  accepts_nested_attributes_for  :images
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.all
  end

  def new
    @product = Product.new
     @product.images.build
  end

  def create
    image_attr = product_params["images_attributes"]["0"]["photo"]
    product_params.delete(:images_attributes)
    @product = Product.new(product_params)
    if @product.save
      image_attr.each do | im |
        image = Image.new(photo: im, entity: @product)
        # Image.new(photo: im, entity_id: @product.id, entity_type: @product.class)
        image.save(validate: false)
      end
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end
  def image
    @product = Product.find(params[:id])
  end
  def make_payment
    @product = Product.find_by_id params[:product_id]
  end
  def process_payment
      @product = Product.find_by_id params[:product_id]
      @result = Braintree::Transaction.sale(
      :amount => @product.price,
      :credit_card => {
        :number => params[:credit_card_number],
        :expiration_date => params["date"]["expiry_date(2i)"] + "/" + params["date"]["expiry_date(1i)"]
      },
      :options=> {
                      store_in_vault: true
                    })
    if @result.success?
      current_user.update_columns(braintree_customer_id: @result.transaction.customer_details.id)
      redirect_to :action=>"index", notice: "Congraulations! Your transaction has been successfully!"
    else
      redirect_to :action=>"index", notice: "Transaction fail"
    end
  end
  def product_params
    params.require(:product).permit!
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/image.html.erb
<%= @product.images.to_json %>

app/views/products/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Product Images</th>
    <th>Name</th>
    <th>Brand</th>
    <th>Size</th>
    <th>Price</th>
    </tr>
    <% @product.each do | product | %>
      <tr>
        <td>
          <% unless product.images.nil? %>
            <% product.images.each do | image | %>
            <%= image_tag image.photo(:thumb) %>
            <%end%>
          <%end%>
        </td>
        <td><%= product.name %></td>
        <td><%= product.brand %></td>
        <td><%= product.size %></td>
        <td><%= product.price %></td>
        <td><%= link_to "Buy", "/purchase_item?product_id=#{product.id}"%></td>
      </tr>
    <%end%>
  </table>
<%= link_to "Add product", new_product_path%>

app/views/products/make_payment.html.erb
<%= form_tag action: "process_payment", method: :post, product_id: params[:product_id] do %>
  <table>
  <%= label_tag :item_value%>
  <%= text_field_tag :item_value, @product.price, readonly: true%>
  <%= label_tag :first_name%>
  <%= text_field_tag :first_name%>
  <%= label_tag :last_name%>
  <%= text_field_tag :last_name%>
  <%= label_tag :company%>
  <%= text_field_tag :company%>
  <%= label_tag :email%>
  <%= text_field_tag :email%>
  <%= label_tag :phone%>
  <%= text_field_tag :phone%>
  <%= label_tag :credit_card_number%>
  <%= text_field_tag :credit_card_number%>
  <%= label_tag :expiry_date%>
  <%= date_select :date, :expiry_date%>
  <%= submit_tag "Buy"%>
  </table>
<%end%>

app/views/products/new.html.erb
<% if @product.errors.full_messages.any? %>
<ul>
  <% @product.errors.full_messages.each do |error_message| %>
    <li><%= error_message %> </li>
  <% end %>
  </ul>
<% end %>

<%= form_for @product do | f| %>
  <table class="table table-striped">
    <tr>
        <td><%= f.label :name%></td>
        <td><%= f.text_field :name%></td>
      </tr>
        <tr>
          <td><%= f.label :brand%></td>
          <td><%= f.text_field :brand%></td>
      </tr>
      <tr>
        <td><%= f.label :size%></td>
        <td><%= f.select :size, %w(M S L XL XXL)%></td>
    </tr>
    <tr>
      <td><%= f.label :price%></td>
      <td><%= f.text_field :price%></td>
    </tr>
    <tr>
      <%= f.fields_for :images  do | im |%>
        <td><%= im.label :photo%></td>
        <td><%= im.file_field :photo, multiple: true%></td>
      <%end%>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit "Add Product"%></td>
    </tr>
  </table>
<%end%>

<!-- %= link_to "Home", products_path% -->

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>